services:
  prov1:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - YA_RUNTIME_OUTBOUND_GIT_CLONE_CACHE_TOKEN=${YA_RUNTIME_OUTBOUND_GIT_CLONE_CACHE_TOKEN:-1}
    env_file:
      - ../common_yagna_config.env
      - prov1.env
    command: ./run_provider.sh

  # Copy configs to prov2, prov3, etc. if you need more providers