services:
  centralnet:
    build:
      dockerfile: Dockerfile
      context: ../../centralnet
    command: ./run_centralnet.sh
  prov-vm1:
    build:
      dockerfile: Dockerfile
      context: ../../provider
      args:
        - YAGNA_RELEASE_TAG=${YAGNA_RELEASE_TAG:-pre-rel-v0.13.0-raw-rc4}
        - RUNTIME_OUTBOUND_RELEASE_TAG=${RUNTIME_OUTBOUND_RELEASE_TAG:-v0.3.5}
        - RUNTIME_VM_RELEASE_TAG=${RUNTIME_VM_RELEASE_TAG:-NO_INSTALL}
    env_file:
      - yagna_config.env
      - prov1.env
    environment:
      - PROVIDER_ENABLE_VM=true
    command: ./run_provider.sh
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/kvm:/dev/kvm
  prov-vm2:
    build:
      dockerfile: Dockerfile
      context: ../../provider
      args:
        - YAGNA_RELEASE_TAG=${YAGNA_RELEASE_TAG:-pre-rel-v0.13.0-raw-rc4}
        - RUNTIME_OUTBOUND_RELEASE_TAG=${RUNTIME_OUTBOUND_RELEASE_TAG:-v0.3.5}
        - RUNTIME_VM_RELEASE_TAG=${RUNTIME_VM_RELEASE_TAG:-NO_INSTALL}
    env_file:
      - yagna_config.env
      - prov2.env
    environment:
      - PROVIDER_ENABLE_VM=true
    command: ./run_provider.sh
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/kvm:/dev/kvm
  prov-out:
    build:
      dockerfile: Dockerfile
      context: ../../provider
      args:
        - YAGNA_RELEASE_TAG=${YAGNA_RELEASE_TAG:-pre-rel-v0.13.0-raw-rc4}
        - RUNTIME_OUTBOUND_RELEASE_TAG=${RUNTIME_OUTBOUND_RELEASE_TAG:-v0.3.5}
        - RUNTIME_VM_RELEASE_TAG=${RUNTIME_VM_RELEASE_TAG:-NO_INSTALL}
    env_file:
      - yagna_config.env
      - prov3.env
    environment:
      - PROVIDER_ENABLE_OUTBOUND=true
    command: ./run_provider.sh
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/kvm:/dev/kvm
  req:
    build:
      dockerfile: Dockerfile
      context: ../../requestor
      args:
        - YAGNA_RELEASE_TAG=${YAGNA_RELEASE_TAG:-pre-rel-v0.13.0-raw-rc4}
    volumes:
      - "./yagna_dir:/root/.local/share/yagna"
    environment:
      - GSB_URL=tcp://0.0.0.0:7464
      - YAGNA_API_URL=http://0.0.0.0:7465
      - YAGNA_APPKEY=${YAGNA_APPKEY}
      - YAGNA_AUTOCONF_ID_SECRET=${YAGNA_AUTOCONF_ID_SECRET}
      - YAGNA_AUTOCONF_APPKEY=${YAGNA_APPKEY}
    command: ./run_requestor.sh
    ports:
      - "3333:3333"
      - "7464:7464"
      - "7465:7465"
    env_file:
      - yagna_config.env
  vpn:
    build:
      dockerfile: Dockerfile
      context: ../../vpn_client
      args:
        - CONNECTOR_RELEASE_TAG=${CONNECTOR_RELEASE_TAG:-v0.2.6}
    environment:
      - YAGNA_APPKEY=${YAGNA_APPKEY}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    command: ./run_vpn_client.sh
    ports:
      - "3336:3336"
